name: Sol Dev Blog
title: Sol Dev Blog
description: This is Sol's Dev Blog
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: hslyjy@gmail.com
disqus_username: Sol
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
